# Generated by Django 5.2.7 on 2026-07-27 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_course_name_coursemajor'),
        ('accounts', '0004_alter_customuser_role_alter_parentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.coursemajor'),
        ),
    ]
